"""Record one real runtime conversation as a dev fixture.

Everything the browser-mode mock replays comes from here, so the design can be
iterated without a Rust build and without inventing data.
"""
import json, os, subprocess, sys, tempfile, threading

REPO = r"C:\Users\SAMSUNG\dev\rigorloom-trackC"
serve = REPO + r"\runtime\scripts\serve.py"
src = REPO + r"\tests\corpus\forms\converted\gianmun-byeolji-1ho.hwpx"
out = REPO + r"\desktop\src\fixtures\corpus.json"

root = tempfile.mkdtemp(prefix="rlfix")
env = dict(os.environ)
env["PYTHONIOENCODING"] = "utf-8"
p = subprocess.Popen([sys.executable, serve, "--entry", "host", "--root", root],
                     stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                     stderr=subprocess.DEVNULL, env=env)
n = [0]


def call(method, params=None):
    n[0] += 1
    f = {"kind": "request", "id": str(n[0]), "method": method}
    if params:
        f["params"] = params
    p.stdin.write((json.dumps(f) + "\n").encode())
    p.stdin.flush()
    box = []
    th = threading.Thread(target=lambda: box.append(p.stdout.readline()), daemon=True)
    th.start()
    th.join(180)
    if not box or not box[0]:
        raise SystemExit("timeout on " + method)
    frame = json.loads(box[0])
    if frame.get("kind") != "response":
        raise SystemExit("error on %s: %s" % (method, json.dumps(frame)[:300]))
    return frame["result"]


call("initialize", {"protocolVersion": "0",
                    "client": {"name": "fixture", "version": "0"},
                    "unknownFieldPolicy": "reject"})
caps = call("capabilities/list")
opened = call("workspace/openPath", {"path": src})
sid = opened["sessionId"]
inspect = call("document/inspect", {"sessionId": sid})
cells = [{"table": t["index"], "row": c["addr"]["row"], "col": c["addr"]["col"]}
         for t in inspect["graph"]["tables"] for c in t["cells"]]
region = call("document/readRegion", {"sessionId": sid, "regions": cells})

p.stdin.close()
p.wait(30)

# Identity is regenerated by the mock, so the fixture stays session-agnostic.
fixture = {
    "_note": "Recorded from a real Runtime v0 session against "
             "tests/corpus/forms/converted/gianmun-byeolji-1ho.hwpx. "
             "Regenerate with desktop/scripts/record-fixture.py.",
    "capabilities": caps,
    "source": opened["source"],
    "inspect": inspect,
    "regions": region["regions"],
}
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8") as fh:
    json.dump(fixture, fh, ensure_ascii=False, indent=1, sort_keys=True)
print("wrote", out, os.path.getsize(out), "bytes")
